In [1]:
import tensorflow as tf
import nltk
from nltk.corpus import stopwords
import re
import pickle
from tensorflow.keras.layers import Conv1D, Bidirectional, LSTM, Dense, Input, Dropout
from tensorflow.keras.layers import SpatialDropout1D, Embedding, SpatialDropout1D

In [2]:
physical_devices = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [3]:
nltk.download('stopwords')
handle=open('tokenizer.pickle', 'rb')
tokenizer1 = pickle.load(handle)
stop_words_test = stopwords.words('english')

[nltk_data] Downloading package stopwords to /home/arnav/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
def preprocess_test(text):
    text = re.sub("@\S+|https?:\S+|http?:\S|[^A-Za-z0-9]+", ' ', str(text).lower()).strip()
    cleaned_text = []
    for token in text.split():
        if token not in stop_words_test:
                cleaned_text.append(token)
    tokens=tf.keras.preprocessing.sequence.pad_sequences(tokenizer1.texts_to_sequences([" ".join(cleaned_text)],),
                        maxlen = 30)
    return tokens

In [5]:
modelelu=tf.keras.models.load_model("my_h5_model2.h5")

In [15]:
text='Finally our new location is open. Peak fitness gym/altitude training &amp; Swim centre. TAYLORS LAKES https://t.co/LtYlB4tyuZ'

In [16]:
text=preprocess_test(text)

In [17]:
text

array([[    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,   142,    27,
         2981,   443,  5899,  4389,   563, 25273,  1091,    21,  1543,
         3592, 15016, 10769]], dtype=int32)

In [18]:
modelelu.predict(text)

array([[0.15170759, 0.84829247]], dtype=float32)

In [19]:
text="@Hossylass @GeorgeMonbiot My dominant hand is totally useless. I may never be able to ride my 🏍 again. Can't even h… https://t.co/GEWO2ofaL6"

In [20]:
text=preprocess_test(text)

In [21]:
text

array([[    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     1, 26859,   662,   284,  2962,   229,    83,   353,
          592,    72,  1099]], dtype=int32)

In [22]:
modelelu.predict(text)

array([[0.7583315, 0.2416685]], dtype=float32)